function init(self)
	msg.post(".", "acquire_input_focus")
end

function final(self)
	msg.post(".", "release_input_focus")
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action.pressed and gui.pick_node(gui.get_node("level_1"), action.x, action.y) then
		msg.post("game:/level_controller", "level_1")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_2"), action.x, action.y) then
		msg.post("game:/level_controller", "level_2")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_3"), action.x, action.y) then
		msg.post("game:/level_controller", "level_3")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_4"), action.x, action.y) then
		msg.post("game:/level_controller", "level_4")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_5"), action.x, action.y) then
		msg.post("game:/level_controller", "level_5")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_6"), action.x, action.y) then
		msg.post("game:/level_controller", "level_6")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_7"), action.x, action.y) then
		msg.post("game:/level_controller", "level_7")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_8"), action.x, action.y) then
		msg.post("game:/level_controller", "level_8")
	end
	if action.pressed and gui.pick_node(gui.get_node("level_9"), action.x, action.y) then
		msg.post("game:/level_controller", "level_9")
	end
	if action.pressed and gui.pick_node(gui.get_node("testing"), action.x, action.y) then
		msg.post("game:/level_controller", "level_test")
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
